name: Generate Snake Animation

permissions:
  contents: write
  
on:
  schedule:
  - cron: "55 19 * * *"
  workflow_dispatch:     # Allow manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: iftikhoq 
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=%23FFFFFF

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Generated snake animation"
          add: "dist/*.svg"
